# Generated by Django 4.2.23 on 2025-08-20 13:06

from django.db import migrations

def create_tables(apps, schema_editor):
    Table = apps.get_model('bookings', 'Table')
    tables = [
        {'number': 1, 'seats': 2},
        {'number': 2, 'seats': 4},
        {'number': 3, 'seats': 4},
        {'number': 4, 'seats': 6},
        {'number': 5, 'seats': 6},
        {'number': 6, 'seats': 8},
    ]
    for table in tables:
        Table.objects.create(**table)

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migration.RunPython(create_tables, reverse_create_tables),
    ]
